epic_kitchen:
  # Common configuration items (all datasets have these)
  scene: null
  cache_dir: null
  resize_shape: null
  patch_size: null
  num_frames: null
  all_frames: false   
  use_gt_depth: false

  mask_estimation: null
  mask_flow_model: null
  mask_binary_open_value: null 

  frame_sampler: pretrain_interval
  frame_max_interval: 4

  # Dataset-specific configuration items
  max_clip_per_video: 1200
  clip_frame: 20
  original_base_root: ./cache/original_datasets/EpicKitchen/EPIC-KITCHENS
  intrinsic_root: none
  pre_save_root: ./cache/processed_datasets