fpha:
  # Common configuration items (all datasets have these)
  scene: null
  cache_dir: null
  resize_shape: null
  patch_size: null
  num_frames: null
  all_frames: false 
  use_gt_depth: false

  mask_estimation: ['egohos']
  mask_flow_model: null
  mask_binary_open_value: null 

  frame_sampler: pretrain_interval
  frame_max_interval: 4

  # Dataset-specific configuration items
  clip_frame: 20
  original_base_root: ./cache/original_datasets/FPHA
  pre_save_root: ./cache/processed_datasets